name: Build Kivy Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Usando Python 3.10 para compatibilidade

    - name: Install Buildozer
      run: |
        pip install buildozer

    - name: Install Buildozer Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses-dev libbz2-dev libssl-dev libsqlite3-dev

    - name: Build Android APK
      # AQUI ESTÁ A CORREÇÃO: Usando 'working-directory' para garantir o caminho correto
      working-directory: androidApp # Este é o diretório RELATIVO à raiz do repositório
      run: |
        buildozer android debug

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kivy-App-APK
        path: bin/*.apk
