name: Build Kivy Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # AQUI ESTÁ A LINHA CORRIGIDA: Alterando para Python 3.8

    - name: Install Buildozer and Cython
      run: |
        pip install buildozer
        pip install cython

    - name: Install Buildozer System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses-dev libbz2-dev libssl-dev libsqlite3-dev automake

    - name: Clean Buildozer Cache
      # Usando o comando padrão 'buildozer clean' para uma limpeza controlada.
      working-directory: androidApp
      run: |
        buildozer clean

    - name: Build Android APK
      working-directory: androidApp
      run: |
        buildozer android debug

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kivy-App-APK
        path: bin/*.apk
